<?xml version="1.0" encoding="UTF-8"?>
<definitions
	xmlns="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
	xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" 
	xmlns:doservice="http://dispatcher.congress.osgisamples.com" 
	xmlns:curr="http://www.osgisamples.com/services/doservice" 
	targetNamespace="http://www.osgisamples.com/services/doservice">

	<types>
		<xs:schema>
			<xs:import namespace="http://dispatcher.congress.osgisamples.com" 
					schemaLocation="xsd/CongressRegistration.xsd"/>
		</xs:schema>
	</types>

	<message name="CongressRegistrationRequestMsg">
		<part name="theInputMessage" element="doservice:CongressRegistrationRequest" />
	</message>

	<message name="CongressRegistrationResponseMsg">
		<part name="theResponseMessage" element="doservice:CongressRegistrationResponse" />
	</message>

	<portType name="SOAPDispatcher">
		<operation name="doService">
			<input name="CongressRegistrationRequest" message="curr:CongressRegistrationRequestMsg"/>
			<output name="CongressRegistrationResponse" message="curr:CongressRegistrationResponseMsg" />
		</operation>
	</portType>

	<binding name="congressSoapBinding" type="curr:SOAPDispatcher">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<operation name="doService">
			<soap:operation soapAction="" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>

	<service name="SOAPDispatcherService">
		<port binding="curr:congressSoapBinding" name="congress">
			<soap:address location="http://localhost:81/services/congress" />
		</port>
	</service>
</definitions>
