//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.19 at 01:56:25 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dispatcher.congress.osgisamples.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.osgisamples.congress.schema;
