//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.19 at 05:00:53 PM CEST 
//


package com.osgisamples.congress.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://dispatcher.congress.osgisamples.com}Congress"/>
 *         &lt;element ref="{http://dispatcher.congress.osgisamples.com}Registrant"/>
 *         &lt;element ref="{http://dispatcher.congress.osgisamples.com}Sessions"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "congress",
    "registrant",
    "sessions"
})
@XmlRootElement(name = "CongressRegistrationRequest")
public class CongressRegistrationRequest {

    @XmlElement(name = "Congress", required = true)
    protected Congress congress;
    @XmlElement(name = "Registrant", required = true)
    protected Registrant registrant;
    @XmlElement(name = "Sessions", required = true)
    protected Sessions sessions;
    @XmlAttribute
    protected String version;

    /**
     * Gets the value of the congress property.
     * 
     * @return
     *     possible object is
     *     {@link Congress }
     *     
     */
    public Congress getCongress() {
        return congress;
    }

    /**
     * Sets the value of the congress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Congress }
     *     
     */
    public void setCongress(Congress value) {
        this.congress = value;
    }

    /**
     * Gets the value of the registrant property.
     * 
     * @return
     *     possible object is
     *     {@link Registrant }
     *     
     */
    public Registrant getRegistrant() {
        return registrant;
    }

    /**
     * Sets the value of the registrant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Registrant }
     *     
     */
    public void setRegistrant(Registrant value) {
        this.registrant = value;
    }

    /**
     * Gets the value of the sessions property.
     * 
     * @return
     *     possible object is
     *     {@link Sessions }
     *     
     */
    public Sessions getSessions() {
        return sessions;
    }

    /**
     * Sets the value of the sessions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sessions }
     *     
     */
    public void setSessions(Sessions value) {
        this.sessions = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
