//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.19 at 05:00:53 PM CEST 
//


package com.osgisamples.congress.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://dispatcher.congress.osgisamples.com}CongressId"/>
 *         &lt;element ref="{http://dispatcher.congress.osgisamples.com}CongressName"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "congressId",
    "congressName"
})
@XmlRootElement(name = "Congress")
public class Congress {

    @XmlElement(name = "CongressId")
    protected Integer congressId;
    @XmlElement(name = "CongressName")
    protected String congressName;

    /**
     * Gets the value of the congressId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCongressId() {
        return congressId;
    }

    /**
     * Sets the value of the congressId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCongressId(Integer value) {
        this.congressId = value;
    }

    /**
     * Gets the value of the congressName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCongressName() {
        return congressName;
    }

    /**
     * Sets the value of the congressName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCongressName(String value) {
        this.congressName = value;
    }

}
